server:
  port: 8821

spring:
  datasource:
    username: root
    password: root
    #url中test为对应的数据库名称
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.uzju.dongtai_sql_inject_lab.entity

#showSql
logging:
  level:
    com.uzju.dongtai_sql_inject_lab.mapper: DEBUG